SymfonyCasts/reset-password-bundle

.github/workflows/ci.yml, .gitignore, composer.json, phpunit.xml.dist
Actions CI tests will fail as is; there are a couple fixes to be done in the test suite under a subsequent PR.
composer.json is in a minimal/invalid state (no name, description, license, etc..) until bundle is ready for release..
=> [repo] add basic files for the repo

LICENSE.md, composer.json, src/Resources/config/reset_password_services.xml
- added the MIT license file to the repo
- declared MIT license in composer.json
existing project files will get updated license header in future PR.
=> add MIT license

src/DependencyInjection/Configuration.php
- update parameter descriptions to better reflect their intended usage.
- fixed ryan's email
- added missing EOF extra line
refs issue #2 fix configuration descriptions
=> minor refactoring of the bundle configuration

src/Persistence/Repository/ResetPasswordRequestRepositoryTrait.php, src/Persistence/ResetPasswordRequestRepositoryInterface.php
ResetPasswordRequestRepositoryInterface::class & trait
=> added missing return type on persistResetPasswordRequest()

.github/workflows/ci.yml, composer.json, psalm.xml
- analyze `src/` files
- ignore `src/tests/`
- using psalm defaults
- ignore possible null reference and possible undefined method in `Configuration::class` 
fixes issue #10
=> add psalm static analysis

src/DependencyInjection/SymfonyCastsResetPasswordExtension.php, src/ResetPasswordHelper.php, src/Resources/config/reset_password_services.xml, src/tests/UnitTests/ResetPasswordHelperTest.php
- improved docBlocks
- re-arrange constructor args (services first, options last)
- improved internal variable naming conventions
- fixed invalid null return type
- improved method naming conventions
- removed old use statements from earlier development
refs issue #7 
further tesitng improvements to be handled in separate PR
=> refactor ResetPasswordHelper & associated tests

src/ResetPasswordHelper.php, src/ResetPasswordHelperInterface.php
=> add getter for token lifetime

src/Persistence/Repository/ResetPasswordRequestRepositoryTrait.php
- added trait summary
- fixed Ryan's email
closes #5
=> update repo trait docBlock

src/ResetPasswordHelperInterface.php
- added method summaries & descriptions where appropriate
- updated Ryan's email
closes #26
=> update helper interface docBlocks

src/Controller/ResetPasswordControllerTrait.php
=> fixed invalid null return type if token does not exist in session

src/DependencyInjection/SymfonyCastsResetPasswordExtension.php, src/SymfonyCastsResetPasswordBundle.php
alias added to allow `symfonycasts_reset_password`
=> set correct bundle alias

src/Persistence/ResetPasswordRequestRepositoryInterface.php
add summaries to methods and param tags where needed.
closes issue #6
=> add repo interface method summaries

src/Command/ResetPasswordRemoveExpiredCommand.php, src/Generator/ResetPasswordRandomGenerator.php, src/Model/ResetPasswordRequestTrait.php, src/ResetPasswordHelper.php
- add forward slash to native functions
=> squash cs-fixer squawks - code related

.php_cs.dist
- cs-fixer itself is required under PR #32
=> add cs-fixer config

src/Model/ResetPasswordRequestInterface.php, tests/Fixtures/ResetPasswordRequestTestFixture.php, tests/UnitTests/Model/ResetPasswordRequestTraitTest.php
- added method summaries
- added missing return type for getUser method
- fixed Ryan's email
=> refactor ResetPasswordRequestInterface

src/Controller/ResetPasswordControllerTrait.php, tests/Fixtures/ResetPasswordRequestTestFixture.php, tests/UnitTests/Controller/ResetPasswordControllerTraitTest.php
=> removed strict type

.github/workflows/ci.yml
disable composer cache in CI temporarily
refs #68
=> [CI] temp disable composer cache

src/Resources/config/reset_password_services.xml, tests/IntegrationTests/ResetPasswordServiceDefinitionTest.php
fixes wrong fake repository class defined in bundle service
=> fixed incorrect fake repo namespace

CHANGELOG.md
Not sure exactly how we were going to document the changes.. But this can be used in the interim until that's figured out. Or closed if another solution is in place.
=> created changelog

src/ResetPasswordHelper.php, tests/UnitTests/ResetPasswordHelperTest.php
=> Fix typo hasUserHisThrottling to hasUserHitThrottling (his/hit)

src/Persistence/Repository/ResetPasswordRequestRepositoryTrait.php
The ORM is not the only Doctrine project having the concept of a repository.
=> Clarify that the repository trait is for Doctrine ORM only

.github/workflows/ci.yml
- Implement Symfony 5.1.* in tests
- Change Symfony dev branch from master to main
=> update symfony version to test against in CI

CHANGELOG.md, composer.json, src/Model/ResetPasswordToken.php, src/ResetPasswordHelper.php, src/Resources/translations/ResetPasswordBundle.en.xlf, tests/UnitTests/Model/ResetPasswordTokenTest.php
- Fixes the long standing issue of possible incorrect token expiration interval
- Adds support to translate token expiration in templates
closes #119
=> improve token expiration

CHANGELOG.md, src/Resources/translations/ResetPasswordBundle.sr.xlf
Mirrors https://github.com/SymfonyCasts/verify-email-bundle/pull/54
=> add Serbian translations

src/Resources/translations/ResetPasswordBundle.tr.xlf
=> Turkish translation file

CHANGELOG.md
*June 30th, 2021*
- [#170](https://github.com/SymfonyCasts/reset-password-bundle/pull/170) - Add correct source and target language to xlf files - *@nicodemuz*
=> [release] v1.9.0

src/Resources/translations/ResetPasswordBundle+intl-icu.nl.xlf
sourced from https://github.com/SymfonyCasts/verify-email-bundle/pull/60
=> [translations] add Dutch translations

src/Resources/translations/ResetPasswordBundle.cs.xlf
Add Czech translations contributed by @jnovakdev in https://github.com/SymfonyCasts/verify-email-bundle/pull/80
=> [translations] add Czech translations

composer.json
Stable test CI runs to be introduced in PR #190
=> add support for symfony 6

CHANGELOG.md
*October 4th, 2022*
- [#245](https://github.com/symfonycasts/reset-password-bundle/pull/245) - [translations] add additional Polish translations and fix pluralizations - *@Flower7C3*
- [#242](https://github.com/symfonycasts/reset-password-bundle/pull/242) - [translations] Additional German translations - *@dennis-g*
_Generated by Git Released_
=> [git-released] v1.16.0

README.md
=> README change - preventing localhost URI for prod

.github/workflows/ci.yml, .github/workflows/static.yaml, composer.json, psalm.xml
- Test against PHP 8.2
- Split Static vs PHPUnit CI Config
=> [ci] housekeeping

composer.json, tests/Fixtures/Entity/ResetPasswordTestFixtureRequest.php, tests/Fixtures/Entity/ResetPasswordTestFixtureUser.php
- add doctrine/annotations to require-dev
- cs fixes
=> chore: fix ci

.php-cs-fixer.dist.php, src/Command/ResetPasswordRemoveExpiredCommand.php, src/ResetPasswordHelper.php, tests/FunctionalTests/Persistence/ResetPasswordRequestRepositoryTest.php, tests/UnitTests/Controller/ResetPasswordControllerTraitTest.php, tests/UnitTests/Generator/ResetPasswordTokenGeneratorTest.php, tests/UnitTests/ResetPasswordHelperTest.php, tests/UnitTests/Util/ResetPasswordCleanerTest.php
After some changes upstream in GitHub CI config: https://github.com/SymfonyCasts/.github/pull/2
=> Rebuild CI and fix CS

README.md
=> Fix repository name in the docs

src/Resources/translations/ResetPasswordBundle.ro.xlf
=> Add ro transalation

src/ResetPasswordHelper.php
=> Fix risky falsy comparison thanks to Psalm

.php-cs-fixer.dist.php
=> [ci] update php-cs-fixer config

phpstan-baseline.neon, src/DependencyInjection/Configuration.php, src/Model/ResetPasswordToken.php
- [ci] ignore method.not-found in tree builder
- add array shape for getExpirationMessageData() return type
=> [ci] handle phpstan baseline squawks

src/Resources/translations/ResetPasswordBundle.da.xlf, src/Resources/translations/ResetPasswordBundle.fa.xlf, src/Resources/translations/ResetPasswordBundle.id.xlf
- Only includes time related strings e.g. `hour`, `minute`, etc...
=> [translations] port DA, FA, & ID from VerifyEmailBundle

composer.json, src/ResetPasswordHelper.php, tests/FunctionalTests/ResetPasswordFunctionalTest.php
use the logic in `internal-test-helpers` to dry out this test
=> use internal-test-helpers for app tests

src/Generator/ResetPasswordTokenGenerator.php, src/Model/ResetPasswordRequestTrait.php, src/Model/ResetPasswordTokenComponents.php, src/ResetPasswordHelper.php
=> prevent leaking sensitive data in logs with the `SensitiveParameter` attribute

src/Resources/translations/ResetPasswordBundle.it.xlf
My PR add missing i18n translations for italian
=> [translation] add missing italian translations

.gitattributes
=> Added .neon files to ignore export.

composer.json
=> fix(#343): remove unnecessary ext-json from dependencies
