- src/tests/UnitTests/Generator/ResetPasswordTokenGeneratorTest.php
- src/tests/UnitTests/ResetPasswordHelperTest.php
`[unitTests] fixed missing setUp() return type required by phpunit 8`
fixes phpunit failure on actions CI and local phpunit runs
`[unit-tests] removed unused mock random generator`
the random generator was leftover from an earlier iteration of the bundle, and slipped through the cracks. No longer needed in the `ResetPasswordHelperTest::class`
> [unit-tests] fix ci blockers

- src/Resources/config/reset_password_services.xml
missing "%" in the kernel.secret argument
> fixed typo in token generator service argument

- src/Generator/ResetPasswordTokenGenerator.php
- src/ResetPasswordHelper.php
- src/tests/UnitTests/Generator/ResetPasswordTokenGeneratorTest.php
- fixed probably bug that would allow the reuse of a verifier token on subsequent `getToken()` method calls on the same generator instance.
- changed `getToken()` to `createToken()` to better reflect what the method is doing
- several minor improvement's to associated unit test
refs issue #3
> refactor token generator / unit test

- src/Model/ResetPasswordRequestTrait.php
- src/tests/UnitTests/Model/ResetPasswordRequestTraitTest.php
the consumer may already have a constructor in the request entity. renaming to initialize avoids funky use statements.
> [RequestTrait] renamed constructor to avoid naming collisions

- src/Generator/ResetPasswordTokenGenerator.php
- src/tests/UnitTests/Generator/ResetPasswordTokenGeneratorTest.php
tokens are one-way and not human readable, use a timestamp vs formatted data string for the encoded expiry time in generation
fixes #22
> replace format with timestamp in token generation

- composer.json
- set dev minimum stability to allow development on latest packages
- replaced bloated framework-bundle dependency with components required by the bundle
- prevent use with older symfony versions by adding conflicts
> Update bundle dependencies

- src/Model/ResetPasswordTokenComponents.php
- add descriptions for either method or the method return type
- removed property summaries in favor of getter summaries
closes #4
> refactor token component docBlocks

- src/Generator/ResetPasswordTokenGenerator.php
- tests/UnitTests/Generator/ResetPasswordTokenGeneratorTest.php
We encode the binary output of `hash_hmac` using `base64_encode()` to reduce the string length of the token. Appx. 31% length reduction without compromising integrity.
```
$nativeHexit = $nativeHexit = \hash_hmac('sha256', 'data', 'key', false);
$base64 = \base64_encode(\hash_hmac('sha256', 'data', 'key', true));
self::assertSame(44, \strlen($base64)); // true
self::assertSame(64, \strlen($nativeHexit)); // true
```
> improve hashed token performence

- psalm.xml
- src/Exception/FakeRepositoryException.php
- src/Persistence/Fake/FakeResetPasswordInternalRepository.php
- src/Resources/config/reset_password_services.xml
- tests/UnitTests/Exception/ResetPasswordExceptionTest.php
- tests/UnitTests/Persistence/FakeResetPasswordInternalRepositoryTest.php
With a fresh install, the bundle blocks usage of the Symfony console until `request_password_repository` has been set with an actual instance of `ResetPasswordRequestRepositoryInterface`.  As using the console to create such a repository may be required, this PR introduces a fake repository that is the default place holder until a real repository can be created / set.
The solution to issue #47 will actually create the actual `reset_password.yaml` file.
fixes #46
> add fake repository to allow symfony console on fresh install

- phpunit.xml.dist
- tests/UnitTests/Command/ResetPasswordRemoveExpiredCommandTest.php
- tests/UnitTests/Controller/ResetPasswordControllerTraitTest.php
- tests/UnitTests/Exception/ResetPasswordExceptionTest.php
- tests/UnitTests/Generator/ResetPasswordRandomGeneratorTest.php
- tests/UnitTests/Generator/ResetPasswordTokenGeneratorTest.php
- tests/UnitTests/Model/ResetPasswordRequestTraitTest.php
- tests/UnitTests/Model/ResetPasswordTokenComponentsTest.php
- tests/UnitTests/Persistence/FakeResetPasswordInternalRepositoryTest.php
- tests/UnitTests/Persistence/ResetPasswordRequestRepositoryTraitTest.php
- tests/UnitTests/ResetPasswordHelperTest.php
- tests/UnitTests/Util/ResetPasswordCleanerTest.php
- added test suite declarations in phpunit.xml.dist
- fixed cs-fixer related squawks
- removed constants not needed
breaking out the test suite declarations will allow ci to halt on failures earlier on, if so configured. Will also make it easier to distinguish which test suite has failed. This PR does not modify current CI behavior.
> minor refactoring of the tests suite

- .php_cs.dist
php-cs-fixer checks all files in `/tests`
CI fails until #65 is pulled in
> add test suite to cs fixer

- src/ResetPasswordHelper.php
We were calling `modify()` with the lifetime value immediately after creating the `\DateTimeImmutable` object. Passing the lifetime value in place of `'now'` in the `\DateTimeImmutable` constructor has the same effect..
> removed un-needed modify call on \DateTimeImmutable

- src/Generator/ResetPasswordRandomGenerator.php
- src/Generator/ResetPasswordTokenGenerator.php
- src/Model/ResetPasswordRequestTrait.php
- src/ResetPasswordHelper.php
- tests/UnitTests/Generator/ResetPasswordRandomGeneratorTest.php
- tests/UnitTests/Generator/ResetPasswordTokenGeneratorTest.php
- tests/UnitTests/Model/ResetPasswordRequestTraitTest.php
- tests/UnitTests/ResetPasswordHelperTest.php
The selector length stored in persistence is always 20 char long. 
- fixed column length in request trait
- removed length param in random generator
- refactored token generator and associated tests accordingly
Could be re-introduced in the future if a use case presents it's self.
> fixed selector length

- src/ResetPasswordHelper.php
- Removes `@param` for some helper properties
- DRY out helper docblocks by using `inheritdoc` to utilize the helper interface descriptions.
> refactor helper docblocks

- .github/workflows/ci.yml
- phpunit.xml.dist
- removed un-needed comments
- splits phpunit tests into separate steps
- use github env for all paths
- fixes typo in phpunit config
> improve CI

- .github/workflows/ci.yml
PR fixes CI to actually use the PHP matrix we were previously defining but not using. See issue #82 
We also disable Xdebug in CI as we are not currently using it. 
- added CI steps to match PHP version on runner CI vs PHP version defined in the matrix. If there is a version mismatch, build fails.
If code coverage is introduced in CI, we can create a separate workflow or job for that.
> use php version matrix to set php version

- phpunit.xml.dist
> prevent external deprecations from failing CI tests

- .github/workflows/ci.yml
- Moves composer validation, php-cs-fixer, & psalm to their own jobs in CI.
- Runs CI automatically every 12 hours
closes #88
> split up CI jobs

- .gitattributes
Prevents some files from being downloaded when requiring the bundle in composer with `--prefer-dist`.
- `/docs`
- `/.github` 
- `/tests`
- `.gitattributes`
- `.gitignore`
- `.php_cs.dist`
- `phpunit.xml.dist`
- `psalm.xml`
- ~`README.md`~
closes #80
> ignore dev files in composer downloads

- CHANGELOG.md
- src/Command/ResetPasswordRemoveExpiredCommand.php
- tests/FunctionalTests/Command/ResetPasswordRemoveExpiredCommandTest.php
- command returns `0` upon completion
- refactored success message
- added functional tests for command
fixes #92
> fixed remove-expired CLI command error

- .github/workflows/ci.yml
- composer.json
- tests/Fixtures/AbstractResetPasswordTestKernel.php
Currently CI only tests bundle against latest master branch of Symfony. This PR fixes issue #82 to test the bundle across Symfony:
- 4.4.*
- 5.0.*
- dev-master
Future supported versions will need to be added to the test matrix.
> test bundle across all supported symfony versions

- src/Persistence/Repository/ResetPasswordRequestRepositoryTrait.php
- tests/FunctionalTests/Command/ResetPasswordRemoveExpiredCommandTest.php
- tests/FunctionalTests/Persistence/ResetPasswordRequestRepositoryTest.php
> [bug] increase time before expired requests are garbage collected to 1 week

- src/Exception/TooManyPasswordRequestsException.php
- src/ResetPasswordHelper.php
- tests/UnitTests/Exception/ResetPasswordExceptionTest.php
- tests/UnitTests/Exception/TooManyPasswordRequestsExceptionTest.php
- tests/UnitTests/ResetPasswordHelperTest.php
- added `getAvailableAt()` to get a `DateTime` object for when a reset can be attempted again
- added `getRetryAfter()` to get the number of seconds before a reset can be attempted again (this can be useful for 429 response status codes)
Solution for #101
> [feature] add additional detail to TooManyPasswordRequestsException

- composer.json
- tests/Fixtures/AbstractResetPasswordTestKernel.php
- tests/Fixtures/ResetPasswordTestFixtureRequestRepository.php
- tests/FunctionalTests/Command/ResetPasswordRemoveExpiredCommandTest.php
- tests/FunctionalTests/Persistence/ResetPasswordRequestRepositoryTest.php
- tests/UnitTests/Controller/ResetPasswordControllerTraitTest.php
Bumps the minimum `doctrine/doctrine-bundle` from `^2.0` => `^2.0.3`. This bump introduces the `Doctrine\Common\Persistence` deprecation, which is thrown in the test suite. Tests that were previously utilizing the "Common" namespace have been fixed.
fixes #95 
closes #75
> [dev] stops using doctrine common ns in test suite

- src/Persistence/Repository/ResetPasswordRequestRepositoryTrait.php
- src/Persistence/ResetPasswordRequestRepositoryInterface.php
- tests/Fixtures/Entity/ResetPasswordTestFixtureRequest.php
- tests/FunctionalTests/Persistence/ResetPasswordRequestRepositoryTest.php
A user can have multiple valid requests. This change removes them all when any one of them is used to successfully reset the user's password.
I think the BC break is negligible. Only unfortunate thing is I think the method name no longer implies what should happen here.
> [bug] ensure all requests are removed for user

- .github/workflows/ci.yml
- composer.json
- phpunit.xml.dist
- psalm.xml
- Removes psalm's `MisplacedRequiredParam` issue which is no longer supported.
- Updates CI for Composer 2 usage
- CI runs for `php-cs-fixer` & `psalm` are forced to use PHP 7.4 until both packages fully support PHP 8
Bumps dev dependencies to versions that support PHP 8
- `php-cs-fixer`
- `psalm`
> add PHP 8 support in CI / dev environments

- src/ResetPasswordHelper.php
- tests/UnitTests/ResetPasswordHelperTest.php
PR #135 inadvertently introduced a change where the token `$expiresAt` DateTimeImmutable instance was created without a timezone. (+00:00). This PR reverts that BC so that `$expiresAt` uses PHP's current time zone. 
closes #138
> revert unintended default UTC tz on expiresAt

- CHANGELOG.md
- src/Controller/ResetPasswordControllerTrait.php
- src/Model/ResetPasswordToken.php
- tests/UnitTests/Controller/ResetPasswordControllerTraitTest.php
- tests/UnitTests/Model/ResetPasswordTokenTest.php
It is more desireable to store the `ResetPasswordToken::class` object in the session after it has been generated by the helper vs storing individual properties of the token class in the session.
Adds the following `ResetPasswordControllerTrait::class` methods:
- `setTokenObjectInSession(ResetPasswordToken $token): void`
- `getTokenObjectFromSession(): ?ResetPasswordToken`
Deprecates the following `ResetPasswordControllerTrait:class` methods:
- `setCanCheckEmailInSession()`
- `canCheckEmail()`
These will be removed in version `2.0` of this bundle.
refs #142
> helper methods for storing ResetPasswordToken in session

- CHANGELOG.md
- src/Resources/translations/ResetPasswordBundle.pl.xlf
Polish translation as genitive, so that it works properly with text: "This link will expire in"
> Enhancement: Add Polish translations

- src/Resources/translations/ResetPasswordBundle.fr.xlf
I think "année" & "années" is not appropriate with the context. We should rather say "an" & "ans".
Exemple : 
```
This password expire in 10 years.
Ce mot de passe expire dans 10 ans.
```
> Typo fr translation

- .github/workflows/ci.yml
Use ubuntu 1804 for tests that rely on PHP <7.4. Github released base image ubuntu-latest which uses ubuntu-20.04 - the 20.04 does not have PHP 7.0 - 7.3. Previously, ubuntu-latest was based on ubuntu-18.04
> [CI] run tests on ubuntu 18.04

- src/Controller/ResetPasswordControllerTrait.php
- src/ResetPasswordHelper.php
- src/ResetPasswordHelperInterface.php
Now that we persist the ResetPasswordToken object in the users session when using `make:reset-password` - we need a convenient way to generate a fake token that is only persisted in the session if reset request is made on a non-existent user.
See https://github.com/symfony/maker-bundle/issues/808
> add ability to generate a fake reset token

- .github/workflows/ci.yml
- .php-cs-fixer.dist.php
- composer.json
- removes unnecessary rules that are already included in the `@symfony` rule sets.
this PR keeps with our current practice of going against Symfony conventions in regards to invoking native functions. e.g. for `sprintf()` <- Symfony but in the bundle `\sprintf()`.
Our current practice will be changed to follow Symfony conventions in a separate PR (avoid bloating this one).
https://cs.symfony.com/doc/rules/function_notation/native_function_invocation.html#rule-sets
> [ci] upgrade php-cs-fixer 2.x -> 3.0

- .php-cs-fixer.dist.php
- src/Command/ResetPasswordRemoveExpiredCommand.php
- src/Generator/ResetPasswordRandomGenerator.php
- src/Generator/ResetPasswordTokenGenerator.php
- src/Model/ResetPasswordRequestTrait.php
- src/Model/ResetPasswordToken.php
- src/ResetPasswordHelper.php
- tests/Fixtures/Entity/ResetPasswordTestFixtureRequest.php
- tests/ResetPasswordTestKernel.php
- tests/UnitTests/Generator/ResetPasswordTokenGeneratorTest.php
- tests/UnitTests/Model/ResetPasswordRequestTraitTest.php
- tests/UnitTests/Model/ResetPasswordTokenTest.php
- tests/UnitTests/ResetPasswordHelperTest.php
as mentioned in PR #166 we should follow Symfony conventions in regards to `native_function_invocation` for consistency across the Symfony Eco-System. 
The PR reverts to past practice of using a `\` for all native functions. Instead, we follow Symfonys practice of only using the leading `\` for compiler optimized functions. 
https://cs.symfony.com/doc/rules/function_notation/native_function_invocation.html
> follow symfony coding standards for native function invocation

- src/Model/ResetPasswordRequestTrait.php
Fixes #174
If you enable attribute loading for doctrine, those columns of the trait will be missing. By specifying both annotations and attributes in the trait, people can use annotations or attributes in their entities as they wish.
```
doctrine:
orm:
mappings:
App:
is_bundle: false
type: attribute / annotation
dir: '%kernel.project_dir%/src/Entity'
prefix: 'App\Entity'
alias: App
```
> Allow using PHP 8 attributes for doctrine entities

- CHANGELOG.md
*July 12th, 2021*
- [#176](https://github.com/SymfonyCasts/reset-password-bundle/pull/176) - Allow using PHP 8 attributes for doctrine entities - *@Tobion*
> [release] v1.9.1

- .github/workflows/ci.yml
Symfony flex changed branch names to support PHP 8. This PR lets composer decide which version of flex is appropriate for CI and runs psalm against PHP 8.
> [ci] fix flex version and run psalm against php 8

- composer.json
Symfony 6.0 uses `symfony/deprecation-contracts` @ `^3.0`, we need to allow `2.2` && `3.0` then let composer decide which can be installed based off of the PHP version. Otherwise reset-password cannot be used w/ Symfony 6+
> allow deprecation contracts 3.0

- CHANGELOG.md
*Nov 30th, 2021*
- [#193](https://github.com/SymfonyCasts/reset-password-bundle/pull/193) - allow deprecation contracts 3.0 - *@jrushlow*
> [release] prep 1.11

- src/Generator/ResetPasswordRandomGenerator.php
Fixes this error:
> ERROR: ArgumentTypeCoercion - src/Generator/ResetPasswordRandomGenerator.php:33:35 - Argument 1 of random_bytes expects positive-int, parent type int provided (see https://psalm.dev/193)
>            $bytes = random_bytes($size);
> [ci] Fix Psalm: Specify var type explicitly

- src/Resources/translations/ResetPasswordBundle.fr.xlf
I just saw that the translations have been added for the exceptions, that is awesome thanks.
I have added the translations for French. The one thing people might disagree over is keeping the word `email`, depending on who you talk to they can prefer, `courriel`, `courrier-électronique`, `Mel`, ...
> Add French translations for the exceptions

- src/Model/ResetPasswordRequestTrait.php
The private access modifier could prevent classes from having a level of inheritance. Changing this modifier to protected will allow doctrine to pick up the properties in inherited classes.
> Changed private for protected

- CHANGELOG.md
Howdy Resetters!
We've made it easier to use the bundle with multiple entities that need reset password functionality thanks to @DavidBilodeau1. We've also added French and Spanish translations for exceptions! 
*February 23rd, 2022*
- [#216](https://github.com/symfonycasts/reset-password-bundle/pull/216) - Changed private to protected for the ResetPasswordRequestTrait - *@DavidBilodeau1*
- [#215](https://github.com/symfonycasts/reset-password-bundle/pull/215) - Added spanish translation for exceptions - *@idmarinas*
- [#214](https://github.com/symfonycasts/reset-password-bundle/pull/214) - Add French translations for the exceptions - *@DennisdeBest*
Diff: https://github.com/symfonycasts/reset-password-bundle/compare/v1.12.0...v1.13.0
Happy Resetting!
---
*February 23rd, 2022*
- …
> [release] v1.13.0

- src/Resources/translations/ResetPasswordBundle.ca.xlf
Added catalan translations to bundle
> Add catalan translations

- CHANGELOG.md
*July 12th, 2022*
- [#229](https://github.com/symfonycasts/reset-password-bundle/pull/229) - Add catalan translations - *@victormhg*
- [#230](https://github.com/symfonycasts/reset-password-bundle/pull/230) - Add missing target-language attr to all translations - *@bocharsky-bw*
_Generated by Git Released_
> [git-released] v1.14.0

- src/Command/ResetPasswordRemoveExpiredCommand.php
This PR fix a deprecation message in ResetPasswordRemoveExpiredCommand.
Message is: 
The "Symfony\Component\Console\Command\Command::$defaultName" property is considered final. You should not override it in "SymfonyCasts\Bundle\ResetPassword\Command\ResetPasswordRemoveExpiredCommand".
I though of putting command name directly in constructor, but I found it more clear to leave it as property.
> [command] Fix Override deprecation

- CHANGELOG.md
*August 6th, 2022*
- [#234](https://github.com/symfonycasts/reset-password-bundle/pull/234) - [command] Fix Override deprecation - *@chindit*
_Generated by Git Released_
> [git-released] v1.14.1

- composer.json
---
https://github.com/php/php-src/issues/8730 has been merged in the `php/php-src` which fixes the `diff()` bug in PHP 8.1. 
Test failed in PHP 8.1 - 8.1.9 ->https://3v4l.org/AZpkv
Test now passes against `master` -> https://3v4l.org/AZpkv/rfc
Once PHP 8.1.10 is released, this PR will prevent users from experiencing this bug in `8.1` through `8.1.9`
fixes #219
> fix expiration diff bug in php 8.1

- src/Persistence/Repository/ResetPasswordRequestRepositoryTrait.php
When using `declare(strict_types=1);` in `ResetPasswordRequestRepositoryTrait`, an error occurs on the token generation because the `getSingleIdentifierValue` method returns a scalar value (in my case an integer because I'm using auto-incremented integers) instead of a string as required by the method.
> chore: fix type cast in `ResetPasswordRequestRepositoryTrait` when using `declare(strict_types=1);`

- src/Persistence/Repository/ResetPasswordRequestRepositoryTrait.php
Not causing any issues, just something I noticed when I moved the implementation to our repository to make some adjustments.
> Fix incorrect case of getOneOrNullResult

- src/Exception/TooManyPasswordRequestsException.php
- src/Generator/ResetPasswordTokenGenerator.php
- src/Model/ResetPasswordToken.php
- src/ResetPasswordHelper.php
- tests/ResetPasswordTestKernel.php
public method signature changes are a non-factor
> [ci] php-cs-fixer it up

- README.md
- src/Persistence/Fake/FakeResetPasswordInternalRepository.php
- src/Persistence/Repository/ResetPasswordRequestRepositoryTrait.php
- src/Persistence/ResetPasswordRequestRepositoryInterface.php
- tests/FunctionalTests/Persistence/ResetPasswordRequestRepositoryTest.php
- tests/UnitTests/Persistence/FakeResetPasswordInternalRepositoryTest.php
> [persistence] remove ResetPasswordRequest objects programmatically

- UPGRADING.md
- src/ResetPasswordHelper.php
`ResetPasswordHelper::class` is now final via `@final` annotation. In version `v2.0.0` this annotation will be replaced with the `final` PHP keyword - preventing it from being extended.
If customization is needed, creating a new helper in userland is recommended.
refs #290
> [ResetPasswordHelper] class to become final

- UPGRADING.md
- src/Command/ResetPasswordRemoveExpiredCommand.php
`ResetPasswordRemoveExpiredCommand::class` is now final via `@final` annotation. In version `v2.0.0` this annotation will be replaced with the `final` PHP keyword - preventing it from being extended.
If customization is needed, creating a new command in userland is recommended.
refs #290
> [command] make class final

- phpstan-baseline.neon
- src/Command/ResetPasswordRemoveExpiredCommand.php
- src/Exception/TooManyPasswordRequestsException.php
- src/Generator/ResetPasswordTokenGenerator.php
- src/Model/ResetPasswordTokenComponents.php
- src/ResetPasswordHelper.php
- src/Util/ResetPasswordCleaner.php
- does not implement promotion in `ResetPasswordToken` - will be done in separate PR
> use constructor property promotion where possible

- CHANGELOG.md
- UPGRADING.md
- src/Command/ResetPasswordRemoveExpiredCommand.php
- set the command name and description using the `#[AsCommand]` Symfony attribute instead of using the `configure()` method / `__constructor()` argument
> [command] use `AsCommand` attribute

- CHANGELOG.md
- UPGRADING.md
- src/Controller/ResetPasswordControllerTrait.php
- tests/Unit/Controller/ResetPasswordControllerTraitTest.php
- Removed deprecated `setCanCheckEmailInSession()` method from trait.
- Removed deprecated `canCheckEmail()` method from trait.
> [trait] remove deprecated methods in `ResetPasswordControllerTrait`

- CHANGELOG.md
- UPGRADING.md
- composer.json
- src/Model/ResetPasswordRequestTrait.php
- tests/Fixtures/Entity/ResetPasswordTestFixtureRequest.php
- tests/Fixtures/Entity/ResetPasswordTestFixtureUser.php
- tests/ResetPasswordTestKernel.php
- tests/Unit/Model/ResetPasswordRequestTraitTest.php
- removes doctrine annotations in the `ResetPasswordRequestTrait`. As a result, attribute mapping is required when using the trait for `ResetPasswordRequest` entities.
- adds property types for class properties
- add the `void` return type to `initialize()`
> [trait] remove annotation support for ResetPasswordRequest objects

- UPGRADING.md
- src/Exception/ResetPasswordRuntimeException.php
- src/Model/ResetPasswordToken.php
- `getToken()` now throws a `ResetPasswordRuntimeException` instead of a `\RuntimeException`
- `getExpirationMessageKey()`, `getExpirationMessageData()`, & `getExpiresAtIntervalInstance()` now throw a `ResetPasswordRuntimeException` if an invalid timestamp was passed for `$generatedAt`. Previously, an unknown
exception may have been thrown if `DateTimeImmutable::createFromFormat()` returned `false` instead of a time object.
- the `LogicException` annotation (completely unrelated to this PR) was replaced as it is being removed in #307
> [token] throws ResetPasswordRuntimeException

- src/Generator/ResetPasswordTokenGenerator.php
- fixes annotation for `$verifier` - missing `null` type
- changes the `$userId` type annotation from `mixed` to `int|string`. In `v2.0` the argument type `int|string` will be added.
_Merge as feature for changelog visibility in release_
> [generator] [1.x] userId argument should be either a string or int

- UPGRADING.md
- src/Generator/ResetPasswordTokenGenerator.php
- adds  `int|string` type for `createToken($userId)`. Previously no type was declared, but `mixed` was annotated in the method docBlock. In #310, `mixed` was changed to `int|string`.
> [generator] add argument type for userId

- UPGRADING.md
- src/Model/ResetPasswordToken.php
- replaces type annotations with property types
- implements constructor property promotion where possible
- requires an `int` to be passed to the now mandatory `$generatedAt` argument when instantiating a new object. The ability to Omit or pass `null` to `$generatedAt` has been deprecated since `v1.2`
> [token] add types and constructor property promotion

- UPGRADING.md
- src/Generator/ResetPasswordTokenGenerator.php
- `createToken()` now throws a `ResetPasswordRuntimeException` when unable to convert the `$verified`, `$userId`, and `$expiresAt` values to json. Previously, we did not ensure that `json_encode()` returned a `string`.
> [generator] throws ResetPasswordRuntimeException when unable to create json

- CHANGELOG.md
*June 6th, 2024*
- [#296](https://github.com/SymfonyCasts/reset-password-bundle/pull/296) - [command] make class final - *@jrushlow*
- [#297](https://github.com/SymfonyCasts/reset-password-bundle/pull/297) - [ResetPasswordHelper] class to become final - *@jrushlow*
- [#305](https://github.com/SymfonyCasts/reset-password-bundle/pull/305) - [trait] add type annotations to ResetPasswordRequestTrait - *@jrushlow*
- [#310](https://github.com/SymfonyCasts/reset-password-bundle/pull/310) - [generator] [1.x] userId argument should be either a string or int - *@jrushlow*
- [#320](https://github.com/SymfonyCasts/reset-password-bundle/pull/320) - Add missing Czech translations - *@dfridrich*
> [release] v1.22.0

- .php-cs-fixer.dist.php
finder `exclude` paths must be relative to the `in` paths. This prevents php-cs-fixer from attempting to scan/fix files in `tests/tmp/cache/etc...`
> [ci] fix wrong tmp path in php-cs-fixer config

- src/ResetPasswordHelper.php
The `generateFakeResetToken()` method previously used a static string (`'fake-token'`) as a placeholder for the fake token. This PR updates it to generate a randomized 32-character hexadecimal string using `bin2hex(random_bytes(16))`. This change improves the security and realism of the fake token by mimicking the structure and appearance of a real token.
> Replacing Static Fake Token with Randomized 32-Character Token

- README.md
This is quite annoying to have this error with the maker bundle:
```
Let's make a password reset feature!
====================================
[ERROR] The file "config/packages/security.yaml" does not exist. PHP & XML configuration formats are currently not
supported.
```
So let's provide the PHP configuration snippets in the doc to ease the process.
This is a maker bundle issue, but the command should allow a `force`parameter to generate the other files even if the PHP configuration is used.
> [docs] add PHP configuration snippets
